### ISSUE TITLE
I couldn't locate this script ~/bin/i3/winmenu.py	

### ISSUE THREAD

**Issue by indykish** [nathantypanski/dotfiles#1]
Great repo. Would be awesome to share this python script you have.

**Comment by christmoore** [comment]
This was removed in commit: ef40358931565f751f32956e2adfcb78416e00e6

I have added winmenu.py to my forked repo if you still wish to see it, and have also asked the creator to re-add the removed script so that others may still see it as well.

**Comment by indykish** [comment]
@MrMepper Cool thanks.
